// AUTO-GENERATED by scripts/gen-version.mjs on each build — do not edit by hand.
export const APP_VERSION = "1.0.4";
export const BUILD = 4;
export const GIT_SHA = "20cd2e5";
export const BUILD_DATE = "2026-09-10";
// Newest-first; used by the deploy seed step to auto-draft a release (see autoDraftRelease).
export const COMMITS: { sha: string; subject: string }[] = [
  {
    "sha": "20cd2e5",
    "subject": "/decode: the quote decoder, on screen"
  },
  {
    "sha": "6b5e249",
    "subject": "Quote decoding: solve the interest rate providers don't print"
  },
  {
    "sha": "872961e",
    "subject": "Stamp the build number from this repository's own history"
  },
  {
    "sha": "5364793",
    "subject": "LeaseWiz: a novated lease explainer, rebased from the RetireWiz codebase"
  }
];
